"/content/drive/MyDrive/copy to Tim/My courses/Ahrefs Academy – Blogging for business"
"/content/drive/MyDrive/copy to Tim/My courses/Alex Becker - Hero Consulting Academy"
"/content/drive/MyDrive/copy to Tim/My courses/Alex Fedotoff - 7 Figure Ecommerce Blueprint"
"/content/drive/MyDrive/copy to Tim/My courses/Anik Singal - Copywriting Academy"
"/content/drive/MyDrive/copy to Tim/My courses/Anton Kraly - DropShip Lifestyle 7.0"
"/content/drive/MyDrive/copy to Tim/My courses/AstroFX Course"
"/content/drive/MyDrive/copy to Tim/My courses/Biaheza Dropshipping Course"
"/content/drive/MyDrive/copy to Tim/My courses/Biaheza's Full Dropshipping Course"
"/content/drive/MyDrive/copy to Tim/My courses/Biaheza's Full Dropshipping Course (1)"
"/content/drive/MyDrive/copy to Tim/My courses/Billy Gene - Clicks Into Customers 2.0"
"/content/drive/MyDrive/copy to Tim/My courses/Billy Willson - 6 Figure Facebook Ads Agency"
"/content/drive/MyDrive/copy to Tim/My courses/Bob Mangat - 7 Figure Agency"
"/content/drive/MyDrive/copy to Tim/My courses/Bob Proctor - The Art of Goal Creation"
"/content/drive/MyDrive/copy to Tim/My courses/Brendan Meyers - Creative Fitness Academy"
"/content/drive/MyDrive/copy to Tim/My courses/Brendon Burchard – 10x Wealth and Business"
"/content/drive/MyDrive/copy to Tim/My courses/Brendon Burchard - Certified High Performance Coaching"
"/content/drive/MyDrive/copy to Tim/My courses/Brendon Burchard – Worlds Greatest Speaker Training"
"/content/drive/MyDrive/copy to Tim/My courses/Carradean Farley - High Ticket Sales for Entrepreneurs"
"/content/drive/MyDrive/copy to Tim/My courses/CF Design School"
"/content/drive/MyDrive/copy to Tim/My courses/Dan Dasilva - 100k Blueprint"
"/content/drive/MyDrive/copy to Tim/My courses/Dan Dasilva - Dropship Academy"
"/content/drive/MyDrive/copy to Tim/My courses/Dan Dasilva - Dropship Academy (1)"
"/content/drive/MyDrive/copy to Tim/My courses/Dan Dasilva - FB Ads Machine 2.0"
"/content/drive/MyDrive/copy to Tim/My courses/Dan Dasilva - Social Marketing Mastery"
"/content/drive/MyDrive/copy to Tim/My courses/Dan Kennedy - Renegade Millionaire 2.0"
"/content/drive/MyDrive/copy to Tim/My courses/Dan Kennedy - The Source Code to Business Success"
"/content/drive/MyDrive/copy to Tim/My courses/Dan Lok - High Ticket Closer Certification 2018"
"/content/drive/MyDrive/copy to Tim/My courses/Dan Lok – Instagram Secret 2019"
"/content/drive/MyDrive/copy to Tim/My courses/Dan Vas-Shopify Freedom"
"/content/drive/MyDrive/copy to Tim/My courses/Dan Vass Shopify Freedom"
"/content/drive/MyDrive/copy to Tim/My courses/Forex Strategy - Elliott Wave Theory with Fibonacci by "/content/drive/MyDrive/copy to Tim/My courses/Alexander ''Alex'' Szweda"
"/content/drive/MyDrive/copy to Tim/My courses/Franklin Hatchett - eCom Elites"
"/content/drive/MyDrive/copy to Tim/My courses/Franklin Hatchett - Ecom Elites 2.0"
"/content/drive/MyDrive/copy to Tim/My courses/Franklin Hatchett - Savage Affiliates"
"/content/drive/MyDrive/copy to Tim/My courses/Gabriel St-Germain - eCom Blueprint"
"/content/drive/MyDrive/copy to Tim/My courses/Golden Option Trading – Forex Course 2019"
"/content/drive/MyDrive/copy to Tim/My courses/Graham Stephan - The YouTube Creator Academy"
"/content/drive/MyDrive/copy to Tim/My courses/Grant Cardone - 10X Growth Conference + Bonuses 2018"
"/content/drive/MyDrive/copy to Tim/My courses/Grant Cardone - Cardone University"
"/content/drive/MyDrive/copy to Tim/My courses/Hayden Bowles - Ecom Remastered 2.0"
"/content/drive/MyDrive/copy to Tim/My courses/Helium 10 Elite - Amazon FBA Masterminds"
"/content/drive/MyDrive/copy to Tim/My courses/Iman Gadzhi - Agency Incubator"
"/content/drive/MyDrive/copy to Tim/My courses/Iman Gadzhi - Influencer Ignited 2.0"
"/content/drive/MyDrive/copy to Tim/My courses/Iman Gadzhi - Six Figure SMMA"
"/content/drive/MyDrive/copy to Tim/My courses/Irek Piekarski - Trading MasterClass"
"/content/drive/MyDrive/copy to Tim/My courses/Jacob Caris - Dream Car Profits"
"/content/drive/MyDrive/copy to Tim/My courses/Jeff Walker - Product Launch Formula 2019"
"/content/drive/MyDrive/copy to Tim/My courses/Jim Kwik - Focus Blueprint"
"/content/drive/MyDrive/copy to Tim/My courses/Jim Kwik – Kwik Learning"
"/content/drive/MyDrive/copy to Tim/My courses/Jim Kwik - Kwik Reading"
"/content/drive/MyDrive/copy to Tim/My courses/Jim Kwik - Kwik Recall Memory Masterclass"
"/content/drive/MyDrive/copy to Tim/My courses/Jim Kwik – Kwik Student"
"/content/drive/MyDrive/copy to Tim/My courses/Jim Kwik - Kwik Thinking"
"/content/drive/MyDrive/copy to Tim/My courses/Jim Kwik Recall – Kwik Learning Online"
"/content/drive/MyDrive/copy to Tim/My courses/Jonathan Smith - Ecom Titans"
"/content/drive/MyDrive/copy to Tim/My courses/Jordan Belfort - Straight Line Marketing"
"/content/drive/MyDrive/copy to Tim/My courses/Jordan Belfort - Straight Line Persuasion"
"/content/drive/MyDrive/copy to Tim/My courses/Jordan Belfort - Straight Line Sales Psychology"
"/content/drive/MyDrive/copy to Tim/My courses/Justin Painter - Dropshipping Mastery Program "
"/content/drive/MyDrive/copy to Tim/My courses/Kevin David - Amazon FBA Ninja"
"/content/drive/MyDrive/copy to Tim/My courses/Kevin David - Digital Course Secrets 2019"
"/content/drive/MyDrive/copy to Tim/My courses/Kevin David - Facebook Ads Ninja Masterclass 2019"
"/content/drive/MyDrive/copy to Tim/My courses/Kody - YouTube Mastery Class"
"/content/drive/MyDrive/copy to Tim/My courses/Live Traders – How To Become A Forex Pro Trader by Anmol Singh"
"/content/drive/MyDrive/copy to Tim/My courses/Live Traders – How To Become A Forex Pro Trader by Anmol Singh (1)"
"/content/drive/MyDrive/copy to Tim/My courses/Matt Par - Make Money On YouTube without Making Videos"
"/content/drive/MyDrive/copy to Tim/My courses/Mikkelsen Twins - Audiobook Income Academy"
"/content/drive/MyDrive/copy to Tim/My courses/Nate Hurst & Clayton Williams – High Ticket Blueprint"
"/content/drive/MyDrive/copy to Tim/My courses/Neel Sarode - Funnel Designer"
"/content/drive/MyDrive/copy to Tim/My courses/Nico Moreno - Messenger Bots for Entrepreneurs"
"/content/drive/MyDrive/copy to Tim/My courses/Paul Joseph - Dropshipping Titans"
"/content/drive/MyDrive/copy to Tim/My courses/Peter Pru – Ecommerce Empire Academy 2019"
"/content/drive/MyDrive/copy to Tim/My courses/Rafael Cintron - 7 Figure Ecommerce Inner Circle"
"/content/drive/MyDrive/copy to Tim/My courses/Robby Blanchard - Commission Hero"
"/content/drive/MyDrive/copy to Tim/My courses/Russell Brunson - Lead Funnels"
"/content/drive/MyDrive/copy to Tim/My courses/Sam Ovens - The Consulting Accelerator "
"/content/drive/MyDrive/copy to Tim/My courses/Sam Ovens - Uplevel Consulting"
"/content/drive/MyDrive/copy to Tim/My courses/Sean Cannell – 10X Your Brand With YouTube"
"/content/drive/MyDrive/copy to Tim/My courses/Sean Cannell - Video Ranking Academy 2.0"
"/content/drive/MyDrive/copy to Tim/My courses/Sebastian Ghiorghiu  - EcomAlphas"
"/content/drive/MyDrive/copy to Tim/My courses/Sebastian Ghiorghiu - Shopify Drop Shipping"
"/content/drive/MyDrive/copy to Tim/My courses/Seller Tradecraft - Amazon Playbook"
"/content/drive/MyDrive/copy to Tim/My courses/Steven Dux – Trading Techniques"
"/content/drive/MyDrive/copy to Tim/My courses/Tai Lopez - Social Media Marketing Agency"
"/content/drive/MyDrive/copy to Tim/My courses/Timothy Sykes - Trading Strategy Collection"
"/content/drive/MyDrive/copy to Tim/My courses/Tim Sanders - Private Label Masters"
"/content/drive/MyDrive/copy to Tim/My courses/Tony Robbins & Dean Graziosi - Knowledge Business Blueprint"
"/content/drive/MyDrive/copy to Tim/My courses/Tristan Broughton - Google Ads Ecom Academy"